coverage:
  status:
    project:
      default:
        target: auto
        threshold: 1%
    patch:
      default:
        target: 98%
        threshold: 1%

ignore:
  - "lib/firebase_options.dart"

comment:
  layout: "reach,diff,flags,files"
  behavior: default
  require_changes: false

