sonar.projectKey=The-Waitlisters_CampusGuide
sonar.organization=the-waitlisters
sonar.projectVersion=1.0


# Sources
sonar.sources=lib
sonar.tests=test
sonar.test.inclusions=test/**

# Coverage
sonar.dart.lcov.reportPaths=coverage/lcov.info
sonar.coverage.exclusions=lib/firebase_options.dart,lib/screens/home_screen.dart,lib/widgets/home/map_layer.dart,lib/widgets/home/campus_map.dart

# Exclude duplication for data + tests
sonar.cpd.exclusions=lib/data/**,test/**

# Other info
sonar.dart.file.suffixes=.dart
sonar.exclusions=**/*.g.dart,**/*.freezed.dart