// Mocks generated by Mockito 5.4.6 from annotations
// in proj/test/widgets/schedule/schedule_overlay_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:mockito/mockito.dart' as _i1;
import 'package:proj/models/course_schedule_entry.dart' as _i5;
import 'package:proj/services/concordia_api.dart' as _i2;
import 'package:proj/services/schedule_lookup.dart' as _i3;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeConcordiaApiService_0 extends _i1.SmartFake
    implements _i2.ConcordiaApiService {
  _FakeConcordiaApiService_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [ScheduleLookupService].
///
/// See the documentation for Mockito's code generation for more information.
class MockScheduleLookupService extends _i1.Mock
    implements _i3.ScheduleLookupService {
  MockScheduleLookupService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.ConcordiaApiService get api =>
      (super.noSuchMethod(
            Invocation.getter(#api),
            returnValue: _FakeConcordiaApiService_0(
              this,
              Invocation.getter(#api),
            ),
          )
          as _i2.ConcordiaApiService);

  @override
  _i4.Future<List<_i5.CourseScheduleEntry>> searchCourse(String? query) =>
      (super.noSuchMethod(
            Invocation.method(#searchCourse, [query]),
            returnValue: _i4.Future<List<_i5.CourseScheduleEntry>>.value(
              <_i5.CourseScheduleEntry>[],
            ),
          )
          as _i4.Future<List<_i5.CourseScheduleEntry>>);
}
