// File generated by FlutterFire CLI.
// coverage:ignore-file
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA52w7FMrp5QAF7Q5P6IDQoZQTR9LYuRC8',
    appId: '1:45831489067:web:b79d1fddfd385d99650c6e',
    messagingSenderId: '45831489067',
    projectId: 'campusguide-8a90f',
    authDomain: 'campusguide-8a90f.firebaseapp.com',
    storageBucket: 'campusguide-8a90f.firebasestorage.app',
    measurementId: 'G-72M8P5M7KW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAJSrZeodDuYjugkmKrfrJbhCFkaH-N434',
    appId: '1:45831489067:android:a12c3aaf5835aa5f650c6e',
    messagingSenderId: '45831489067',
    projectId: 'campusguide-8a90f',
    storageBucket: 'campusguide-8a90f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB_iD6-gXedQs_Iw7Y5d79EcAklqhsUiVk',
    appId: '1:45831489067:ios:3fa3255a03582a4a650c6e',
    messagingSenderId: '45831489067',
    projectId: 'campusguide-8a90f',
    storageBucket: 'campusguide-8a90f.firebasestorage.app',
    iosBundleId: 'com.example.proj',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB_iD6-gXedQs_Iw7Y5d79EcAklqhsUiVk',
    appId: '1:45831489067:ios:3fa3255a03582a4a650c6e',
    messagingSenderId: '45831489067',
    projectId: 'campusguide-8a90f',
    storageBucket: 'campusguide-8a90f.firebasestorage.app',
    iosBundleId: 'com.example.proj',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA52w7FMrp5QAF7Q5P6IDQoZQTR9LYuRC8',
    appId: '1:45831489067:web:690ef59d1feef86f650c6e',
    messagingSenderId: '45831489067',
    projectId: 'campusguide-8a90f',
    authDomain: 'campusguide-8a90f.firebaseapp.com',
    storageBucket: 'campusguide-8a90f.firebasestorage.app',
    measurementId: 'G-NRS80V8DH5',
  );

}